project/urls.py
from django.contrib import admin
from django.urls import path
import blog.views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Pour se connecter
    path('', blog.views.login_page, name="login"),
    # Pour se déconnecter
    path('logout', blog.views.logout_user, name='logout'),
    # Pour s'inscrire
    path('signup/', blog.views.signup_page, name='signup'),

    # Page d'accueil une fois connecter et qui contient tout le contenue crées par les autres utlisateurs
    path('flux/', blog.views.flux, name="flux"),
    # Page qui affiche ses propres critiques et tickets
    path('posts/', blog.views.posts, name='posts'),

    # Page pour créer un ticket
    path('ticket/', blog.views.create_ticket, name="ticket"),
    # Pour modifier un ticket
    path('<int:ticket_id>/ticket_edit/', blog.views.ticket_edit, name='ticket_edit'),
    #Pour supprimer un ticket
    path('<int:ticket_id>/ticket_delete/', blog.views.ticket_delete, name='ticket_delete'),

    # Page pour créer une critique
    path('review/', blog.views.create_review, name="review"),
    # Page pour créer une critique en fonction d'un ticket
    path('<int:ticket_id>/review_ticket/', blog.views.review_ticket, name='review_ticket'),
    # Page pour modifier une critique
    path('<int:review_id>/review_edit/', blog.views.review_edit, name="review_edit"),
    # Page pour supprimer une critique
    path('<int:review_id>/review_delete/', blog.views.review_delete, name="review_delete"),

    # Page pour suivre un utilisateur
    path('follow/', blog.views.follow_view, name='follow'),
    # Pour se désabonner d'un utilisateur
    path('<int:id>/follow_delete/', blog.views.follow_delete, name='follow_delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models


class User(AbstractUser):
    username = models.CharField(
        verbose_name='username',
        max_length=100,
        unique=True
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    first_name = models.CharField('first name', max_length=150, blank=True)
    USERNAME_FIELDS = ('username',)


class Ticket(models.Model):
    titre = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    ticket = models.ForeignKey(Ticket, null=True,
                               on_delete=models.SET_NULL, blank=True)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    # Your UserFollows model definition goes here
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='following'
    )
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='followed_by'
    )

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ('user', 'followed_user',)

blog/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, label='Nom d’utilisateur')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput,
                               label='Mot de passe')


class TicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = ['titre', 'description', 'image']


class ReviewForm(forms.ModelForm):
    choice_value = [('1', '- 1'), ('2', '- 2'), ('3', '- 3'),
                    ('4', '- 4'), ('5', '- 5')]
    rating = forms.ChoiceField(label='Note', widget=forms.RadioSelect,
                               choices=choice_value)
    edit_review = forms.BooleanField(widget=forms.HiddenInput, initial=True)

    class Meta:
        model = models.Review
        fields = ['headline', 'rating', 'body']

blog/views.py
from django.contrib.auth.decorators import login_required
from . import forms
from . import models
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404
from blog.models import UserFollows, Ticket, Review, User
from blog.forms import ReviewForm
from django.contrib import messages
from django.db.models import Q


def login_page(request):
    form = forms.LoginForm()
    message = ''
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                return redirect('flux')

        message = 'Identifiants invalides.'
    return render(
        request, 'blog/login.html', context={'form': form, 'message': message})


def logout_user(request):
    logout(request)
    return redirect('login')


def signup_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        password1 = request.POST.get("password1")
        if password != password1:
            messages.error(request,
                           "Les mots de passe fournit ne correspondent pas")
            return redirect('signup')
        user = User.objects.create_user(username=username, password=password1)
        messages.info(request, f"Création du compte {user.username}"
                               f" effectuée.")
        # auto-login user
        # login(request, user)
        # return redirect('login')
    return render(request, 'blog/signup.html')


@login_required
def flux(request):
    following = UserFollows.objects.filter(user__exact=request.user)
    tickets = models.Ticket.objects.filter(
        Q(user=request.user)
        | Q(user__id__in=following.values_list("followed_user"))
    )
    reviews = models.Review.objects.filter(
        Q(user=request.user)
        | Q(user__id__in=following.values_list("followed_user"))
    )
    print(tickets)
    return render(request, "blog/flux.html", context={'tickets': tickets,
                                                      'reviews': reviews})


@login_required
def posts(request):
    title = "Posts"
    current_user = request.user
    tickets = Ticket.objects.filter(user=current_user)
    for ticket in tickets:
        print(ticket.image)
    reviews = Review.objects.filter(user=current_user)
    context = {"title": title,
               "tickets": tickets,
               "reviews": reviews,
               "current_user": current_user,
               }
    return render(request, "blog/posts.html", context)


@login_required
def create_ticket(request):
    form = forms.TicketForm()
    if request.method == 'POST':
        form = forms.TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect("posts")
    return render(request, 'blog/ticket.html', context={'form_ticket': form})


@login_required
def ticket_edit(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    form = forms.TicketForm(instance=ticket)
    if request.method == 'POST':
        form = forms.TicketForm(request.POST, instance=ticket)
        if form.is_valid():
            form.save()
            return redirect('posts')
    context = {'edit_form': form, 'ticket': ticket}
    return render(request, 'blog/ticket_edit.html', context)


@login_required
def ticket_delete(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)
    ticket.delete()
    return redirect('posts')


@login_required
def create_review(request):
    ticket_form = forms.TicketForm()
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)
        if all([ticket_form.is_valid(), review_form.is_valid()]):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            if ticket_form.cleaned_data['image']:
                ticket.image = ticket_form.cleaned_data['image']
            ticket.has_review = True
            ticket.save()
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = get_object_or_404(models.Ticket, id=ticket.id)
            review.save()
            return redirect('posts')
    context = {
        'ticket': True,
        'ticket_form': ticket_form,
        'review_form': review_form
    }
    return render(request, 'blog/reviews.html', context)


@login_required
def review_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    form = forms.TicketForm(instance=ticket)
    title_page = f"Vous répondez au ticket {ticket.titre}"
    if request.method == 'POST':
        form = forms.TicketForm(request.POST, instance=ticket)
        if form.is_valid():
            form.save()
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.rating = review_form.cleaned_data['rating']
            review.headline = review_form.cleaned_data['headline']
            review.body = review_form.cleaned_data['body']
            review.save()
            return redirect('posts')
    else:
        review_form = ReviewForm()
    context = {
        'title_page': title_page,
        'review_form': review_form,
        'ticket': ticket,
        'form_is_ticket': form
    }
    return render(request, 'blog/reviews.html', context)


@login_required
def review_edit(request, review_id):
    review = get_object_or_404(models.Review, id=review_id)
    form = forms.ReviewForm(instance=review)
    if request.method == 'POST':
        form = forms.ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('posts')
    context = {'edit_form': form, 'review': review}

    return render(request, 'blog/review_edit.html', context)


@login_required
def review_delete(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    review.delete()
    return redirect('posts')


@login_required
def follow_view(request):
    page_title = 'Abonnements'
    followed_by = UserFollows.objects.filter(user=request.user)
    following = models.UserFollows.objects.filter(followed_user=request.user)

    if request.method == 'POST':
        follow_user = request.POST.get('follow_user')
        if follow_user == request.user.username:
            messages.error(request,
                           "Vous ne pouvez pas vous abonner à vous-même")
            return redirect('follow')

        existing_user = User.objects.filter(username=follow_user)

        if existing_user:
            existing_user = User.objects.get(username=follow_user)
            try:
                user_follows = UserFollows(user=request.user,
                                           followed_user=existing_user)
                user_follows.save()
                messages.info(request,
                              f"Vous êtes abonnés à {existing_user.username}")

            except Exception:
                messages.error(request,
                               "Vous êtes déjà abonnés à cet utilisateur")
                return redirect('follow')

        else:
            messages.error(request,
                           "Le nom de l'utilisateur demandé n'existe pas")
            return redirect('follow')

    context = {
        'title_page': page_title,
        'followed_by': followed_by,
        'following': following,
    }
    return render(request, 'blog/follow.html', context)


@login_required
def follow_delete(request, id):
    followed_by = UserFollows.objects.filter(id=id).first()
    if followed_by:
        followed_by.delete()
    return redirect('follow')

blog/templates/blog/_reviews.html
<div class="container">
    <div class="row m-5 p-5 justify-content-around border border-dark bg-secondary text-light">
        <div class="col-6">
            <p class="user">{{ review.user }} a publié une critique en réponse au ticket {{ ticket.user }}</p>
            <h2 class="text-titre">{{ review.headline }} - review {{ rating }}</h2>
            <P class="rating">{{ review.rating }}</P>
            {% load static %}
            {% if review.rating == 0 %}
            <p>
                <span>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png'%}" width='30px'>
                </span>
            {% elif review.rating == 1 %}
                <span>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                </span>
            {% elif review.rating == 2 %}
                <span>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                </span>
            {% elif review.rating == 3 %}
                <span>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                </span>
            {% elif review.rating == 4 %}
                <span>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_blanche.png' %}" width='30px'>
                </span>
            {% elif review.rating == 5 %}
                <span>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                    <img src="{% static 'img/etoile_noire.png' %}" width='30px'>
                </span>
            </p>
            {% endif %}
            <p class="date_review">{{ review.time_created }}</p>
            <h3 class="text-titre"> {{ review.body }} </h3>
            <div class="card-body">
                <h4> Voici le ticket en question : </h4>
                <h4 class="text-titre">Ticket de {{ ticket.user }}</h4>
                <h4 class="text-titre">{{ ticket.titre }}</h4>
                <h4 class="text-titre">{{ ticket.description}}</h4>
                {% if ticket.image %}
                    <img src="{{ticket.image.url}}" width="300px" />
                {% endif %}
            </div>
        </div>
    </div>
</div>

blog/templates/blog/_tickets.html
<div class="row m-5 p-5 justify-content-around border border-dark bg-secondary text-light">
    <div class="col-6">
        <p class="border-bottom border-light fst-italic"> {{ ticket.user }} a créer un ticket </p>
        <p class="border-bottom border-light"> {{ ticket.titre }}  </p>
        <p> {{ ticket.description }} </p>
        {% if ticket.image %}
        <img src="{{ticket.image.url}}" width="100px"/>
        {% endif %}
    </div>
    <div class="col-3 col-center">
        <p class="small border rounded-pill border-light">{{ ticket.time_created|date:"H:i, d F Y" }}</p>
    </div>
</div>

blog/templates/blog/flux.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
        <a href="{% url 'ticket' %}"><button class="button-critique-flux" type="submit" style="width: 12rem;">Demander une critique</button></a>
        <a href="{% url 'review' %}"><button class="button-critique-flux" type="submit" style="width: 12rem;">Créer un critique</button></a>
        {% for ticket in tickets %}
            {% include 'blog/_tickets.html' %}
            {% for review in ticket.review_set.all %}
                {% include 'blog/_reviews.html' %}
            {% empty %}
            <a class="button-flux" href="{% url 'review_ticket' ticket.id %}"><button type="submit" > Créer une critique afin de répondre a ce ticket</button></a>
            {% endfor %}
        {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/follow.html
{% extends 'base.html' %}
{% block content %}
<form method="post" class="form container">
    {% csrf_token %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="row">
                <p></p>
                <p class="h4 col-center border border-dark bg-secondary text-light">Suivre d'autres utilisateurs</p>
                <div class="col-10 text-right" ><br>
                    <input type="text" class="form-control border border-secondary" name="follow_user" placeholder="Nom d'utilisateur"/>
                </div>
                <div class="col-2 text-left" ><br>
                    <button class="btn btn-secondary" value="Submit" type="submit" >Envoyer</button>
                </div>
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <h5 class="text-light bg-danger small fw-bold fst-italic">{{ message }}</h5>
                        {% elif message.tags == 'info' %}
                            <h5 class="text-light bg-secondary small fst-italic">{{ message }}</h5>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="row">
                <p class="h4 col-center border border-dark bg-secondary text-light">Abonnements</p>
                <p></p>
                {% for user_followed in followed_by %}
                    <div class="col-10 border border-secondary bg-light" >
                        <p>{{ user_followed.followed_user }}</p>
                    </div>
                    <div class="col-2 text-left" >
                        <a href="{% url 'follow_delete' id=user_followed.id   %}" onclick="return confirm(
                        'Etes-vous sûr de supprimer cet abonnement ?');">
                        <button class="btn btn-secondary" value="Submit" type="submit" >Envoyer</button>
                        </a>
                    </div>
                {% endfor %}

                <p></p>
                <p class="h4 h4 col-center border border-dark bg-secondary text-light">Abonnés</p>
                <p></p>
                {% for user_following in following %}
                <div class="col-12 border border-secondary bg-light" >
                    <p>{{ user_following.user }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

blog/templates/blog/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <button type="submit" >Se connecter</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2 style="text-align: center;">Vos Posts</h2>
        {% for ticket in tickets %}
            <div class="row m-5 p-5 justify-content-around border border-dark bg-secondary text-light">
            <div class="row justify-content-center">
            <div class="col-6 mt-4">
            <div class="border-bottom border-light fst-italic">Vous avez publié un ticket</div>
            <div class="border-bottom border-light fst-italic">{{ ticket.time_created }}</div>
            <h3 class="border-bottom border-light fst-italic">{{ ticket.titre }}</h3>
            <p class="border-bottom border-light fst-italic">{{ ticket.description }}</p>
            {% if ticket.image %}
                <img class="ticket__image" src="{{ ticket.image.url }}" width="100px">
            {% endif %}
            <a class="btn" href="{% url 'ticket_edit' ticket.pk %}"><button type="submit" > Modifier le ticket </button></a>
            <a class="btn" href="{% url 'ticket_delete' ticket.pk %}"><button type="submit" > Supprimer le ticket </button></a>
    </div>
</div>
            {% for review in ticket.review_set.all %}
                {% include 'blog/_reviews.html' %}
                <a class="btn" href="{% url 'review_edit' review.pk %}"><button type="submit">Modifier la critique</button></a>
                <a class="btn" href="{% url 'review_delete' review.pk %}"><button type="submit">Supprimer la critique</button></a>
            {% empty %}
            <a class="button-flux" href="{% url 'review_ticket' ticket.id %}"><button type="submit" > Créer une critique </button></a>
            {% endfor %}
        {% endfor %}
            </div>
            </div>
{% endblock content %}

blog/templates/blog/review_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <div class="form form_review">
                <h2>Modifier la critique</h2>
                <form method="POST">
                    {{ edit_form.as_p }}
                    {% csrf_token %}
                    <a class="btn" href="{% url 'review_edit' review.pk %}"><button type="submit" >Sauvegarder</button></a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/reviews.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="form form__review">
                <h2>Publier une critique</h2>
                {% if ticket %}
                    <form method="post" enctype="multipart/form-data">
                        <h4>A propos de ce livre:</h4>
                        {{ ticket_form.as_p }}
                        <h4>Ma critique:</h4>
                        {{ review_form.as_p }}
                        {% csrf_token %}
                        <input class="btn" type="submit" value="Soumettre">
                    </form>
                {% else %}
                    <form method="post">
                        {{ form_is_ticket.as_p }}
                        {% csrf_token %}
                        <input class="btn" type="submit" value="Soumettre">
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <h2>Inscription</h2>
            <form method="post">
                {% csrf_token %}
                <p>
                    <label for="username">Nom d'utilisateur</label>
                    <input id="username" type="text" name="username">
                </p>
                <p>
                    <label for="password">Mot de passe</label>
                    <input id="password" type="password" name="password">
                </p>
                <p>
                    <label for="password1">Confirmer le mot de passe</label>
                    <input id="password1" type="password" name="password1">
                </p>
                <button type="submit">S'inscrire</button>
                <a href="{% url 'login' %}"><button type="button">Retour</button></a>
            </form>
            {% if messages %}
                <div class="container">
                    {% for message in messages %}
                        <h5 class="text-light bg-danger small fw-bold fst-italic">{{ message }}</h5>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content%}

blog/templates/blog/ticket.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <h2 style="text-align: center;">Nouveau ticket</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_ticket.as_p }}
                <button type="submit"> Envoyer </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/ticket_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <div class="form form_ticket">
                <h2>Modifier le ticket</h2>
                <form method="POST">
                    {{ edit_form.as_p }}
                    {% csrf_token %}
                    <a class="btn" href="{% url 'ticket_edit' ticket.pk %}"><button type="submit" > Modifier le ticket </button></a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}